pipeline {
    agent any

    environment {
        IMAGE_NAME = "bookmyshow-app"
        CONTAINER_NAME = "bms-container"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/ksandhiya29/devstone.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container for Testing') {
            steps {
                sh '''
                docker run -d -p 5000:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }

        stage('Test Application') {
            steps {
                sh 'curl http://localhost:5000'
            }
        }

        stage('Deploy using Ansible') {
            steps {
                sh 'ansible-playbook ansible/playbook.yml'
            }
        }
    }

    post {
        always {
            sh 'docker stop $CONTAINER_NAME || true'
            sh 'docker rm $CONTAINER_NAME || true'
            sh 'docker rmi $IMAGE_NAME || true'
        }
    }
}
